auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb  # 'boltdb-shipper' yerine 'tsdb' kullanıyoruz
      object_store: filesystem
      schema: v13  # Schema'yı v13'e güncelliyoruz
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index  # Active index'ler için dizin belirtildi
    cache_location: /tmp/loki/index_cache  # Cache dosyaları için dizin belirtildi
  filesystem:
    directory: /tmp/loki/chunks  # Chunk dosyalarının depolanacağı dizin

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false  # Metadata desteğini kapatıyoruz

chunk_store_config: {}

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

compactor:
  working_directory: /tmp/loki/compactor
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem  # 'filesystem' olarak ayarlandı
  # delete_request_directory parametresi kaldırıldı!

common:
  path_prefix: /loki  # Common bölümüne path_prefix ekledik

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
